version: "3.7"

services:
  app:
    build:
      context: ./docker/nginx/1.18
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    build:
      context: ./docker/php/7.3
    links:
      - db
    volumes: *appvolumes

  db:
    image: mysql:5.7
    restart: always
    env_file: env/db.env
    command: [
      '--wait_timeout=28800',
      '--max_allowed_packet=536870912' # Set 512Mb
    ]
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:5.0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node


#  rabbitmq:
#    image: rabbitmq:3.7-management
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    volumes:
#      - rabbitmqdata:/var/lib/rabbitmq

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.3-fpm-6
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  rabbitmqdata:
  sockdata:
  ssldata:
